#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'
module Fabulator
  module Expr
    class Parser < Racc::Parser

module_eval(<<'...end xsm_expression_parser.racc/module_eval...', 'xsm_expression_parser.racc', 151)
  require 'fabulator/expr'

  def parse(t, xml = { })
    @source = t
    @curpos = 0
    @namespaces = { }

    if xml.nil?
      @namespaces = { }
    elsif xml.is_a?(Hash)
      @namespaces = xml
    else
      xml.namespaces.each do |ns|
        @namespaces[ns.prefix] = ns.href
      end
      begin
        @namespaces[''] = xml.namespaces.default.href
      rescue
      end
    end

    @yydebug = true

    @last_token = nil
      
    do_parse
  end

  @@regex = {
    :simple_tokens => %r{\.\.|::|!=|>=|<=|\/\/|:=|\.|@|[*]|\(|\)|\[|\]|\{|\}|\/|\||\+|-|=|>|<|&|,|;},
    :ncname => %r{(?:[a-zA-Z_][-a-zA-Z0-9_.]*)},
    :event_type => %r{(?:processing-instruction|comment|text|node)},
    :axis_name => %r{(?:attribute|child|child-or-self|descendant|descendant-or-self|method|self)},
    :namespace_name => %r{(?:context|global|local|session|universal)},
    :number => %r{(-?\d+(?:\.\d+)?|\.\d+)},
  }

  @@regex[:axis] = %r{(#{@@regex[:ncname]})\s*(?=::)}
  @@regex[:name_colon_star] = %r{(#{@@regex[:ncname]}:\*)}
  @@regex[:qname] = %r{((?:#{@@regex[:ncname]}:)?#{@@regex[:ncname]})}
  @@regex[:dollar_qname] = %r{\$#{@@regex[:qname]}}
  @@regex[:function_name] = %r{#{@@regex[:qname]}\s*(?=\([^:])}

  @@ops = {
    '..' => :DOT_DOT,
    '::' => :COLON_COLON,
    '!=' => :NEQ,
    '>=' => :GTE,
    '<=' => :LTE,
    '//' => :SLASH_SLASH,
    ':=' => :COLON_EQUAL,
    '.'  => :DOT,
    '@'  => :AT,
    '*'  => :STAR,
    '('  => :LP,
    ')'  => :RP,
    '['  => :LB,
    ']'  => :RB,
    '{'  => :LC,
    '}'  => :RC,
    '/'  => :SLASH,
    '|'  => :PIPE,
    '+'  => :PLUS,
    '-'  => :MINUS,
    '='  => :EQ,
    '>'  => :GT,
    '<'  => :LT,
    '&'  => :AMP,
    ','  => :COMMA,
    ';'  => :SEMI
  }

  @@preceding_tokens = { }
  [%{
    @ :: ( 
    and or mod div 
    * 
    / // | + - = != < <= > >=
    == & && ||
  }.split(/\s*/), '[', ',', '$' ].each { |t| @@preceding_tokens[t] = true }

  @@regex[:general] = Regexp.compile(%{^(?:#{@@regex[:function_name]}|#{@@regex[:axis]}|#{@@regex[:name_colon_star]}|#{@@regex[:qname]}|('[^']*'|"[^"]*")|#{@@regex[:number]}|#{@@regex[:dollar_qname]}|(#{@@regex[:simple_tokens]}))})

  def next_token  
    @token = nil
    white_space = 0
    new_line = 0
    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end

    # skip comments delimited by (:  :)
    # comments can be nested
    # these are XPath 2.0 comments
    #
    if @curpos < @source.length && @source[@curpos..@curpos+1] == '(:'
      comment_depth = 1
      @curpos = @curpos + 2
      while comment_depth > 0 && @curpos < @source.length
        if @source[@curpos..@curpos+1] == '(:'
          comment_depth = comment_depth + 1
          @curpos = @curpos + 1
        end
        if @source[@curpos..@curpos+1] == ':)'
          comment_depth = comment_depth - 1
          @curpos = @curpos + 1
        end
        @curpos = @curpos + 1
      end
      white_space = white_space + 1
    end

    while @curpos < @source.length && @source[@curpos..@curpos] =~ /\s/ do
      if @source[@curpos..@curpos] =~ /\n/
        new_line = new_line + 1
      end
      @curpos = @curpos + 1
      white_space = white_space + 1
    end
        
    if @curpos >= @source.length
      @last_token = nil
      return [ false, false ]
    end

    #if new_line > 0 || white_space > 0
    #  @token = [ :SP, '' ]
    #end

    if @token.nil? && @last_token && ! @@preceding_tokens[@last_token[1]]
      if @source[@curpos..@curpos] == '*'
        @token = [ :STAR, '*' ]
      else
        if @source[@curpos..@source.length-1] =~ /^(#{@@regex[:ncname]})/
          ncname = $1
          case ncname
            when 'for':
              @token = [ :FOR, 'for' ]
            when 'return':
              @token = [ :RETURN, 'return' ]
            when 'in':
              @token = [ :IN, 'in' ]
            when 'let':
              @token = [ :LET, 'let' ]
            when 'except':
              @token = [ :EXCEPT, 'except' ]
            when 'every':
              @token = [ :EVERY, 'every' ]
            when 'some':
              @token = [ :SOME, 'some' ]
            when 'satisfies':
              @token = [ :SATISFIES, 'satisfies' ]
            when 'if':
              @token = [ :IF, 'if' ]
            when 'then':
              @token = [ :THEN, 'then' ]
            when 'else':
              @token = [ :ELSE, 'else' ]
            when 'to':
              @token = [ :TO, 'to' ]
            when 'and':
              @token = [ :AND, 'and' ]
            when 'or':
              @token = [ :OR, 'or' ]
            when 'mod':
              @token = [ :MOD, 'mod' ]
            when 'div':
              @token = [ :DIV, 'div' ]
            #when '*doh*':
            #  # do nothing
            #  @token = nil
            else
              @token = nil
          end
        end
      end
    end
 
    if @token.nil? && @source[@curpos..@curpos+1] == '..'
      @token = [ :DOT_DOT, '..' ]
    end

    if @token.nil?
      if @curpos >= @source.length
        @token = [false, false]
        return @token
      end

      res = @@regex[:general].match(@source[@curpos..@source.length-1])
      #@source[@curpos..@source.length-1] =~ @@regex[:general]
      #res = [ nil, $1, $2, $3, $4, $5, $6, $7, $8 ]
      if res.nil?
        raise "Failed to parse '#{@source}' at #{@curpos}': #{@source[@curpos..@source.length-1]}"
      else
        if !res[1].nil?
          if res[1] == 'if'
            @token = [ :IF, 'if' ]
          else
            @token = [ :FUNCTION_NAME, res[1] ]
          end
        elsif !res[2].nil?
          @token = [ res[2] == 'method' ? :AXIS_METHOD : :AXIS_NAME, res[2] ]
        elsif !res[3].nil?
          @token = [ :NAME_COLON_STAR, res[3] ]
        elsif !res[4].nil?
          qname = res[4]
          case qname
            when 'for':
              @token = [ :FOR, 'for' ]
            when 'return':
              @token = [ :RETURN, 'return' ]
            when 'in':
              @token = [ :IN, 'in' ]
            when 'let':
              @token = [ :LET, 'let' ]
            when 'except':
              @token = [ :EXCEPT, 'except' ]
            when 'every':
              @token = [ :EVERY, 'every' ]
            when 'some':
              @token = [ :SOME, 'some' ]   
            when 'satisfies':
              @token = [ :SATISFIES, 'satisfies' ]
            when 'if':
              @token = [ :IF, 'if' ]
            when 'then':
              @token = [ :THEN, 'then' ]
            when 'else':
              @token = [ :ELSE, 'else' ]
            else
              @token = [ :QNAME, res[4] ]
          end
        elsif !res[5].nil?
          s = res[5]
          s = s[1..s.length-2]
          @token = [ :LITERAL, s ]
          @curpos = @curpos + 2  # the quotes
        elsif !res[6].nil?
          @token = [ :NUMBER, res[6] ]
        elsif !res[7].nil?
          @curpos = @curpos + 1
          @token = [ :DOLLAR_QNAME, res[7] ]
        elsif !res[8].nil?
          @token = [ @@ops[res[8]] || res[8], res[8] ]
        else
          raise "Failed to parse '#{@source}' at #{@curpos}: #{@source[@curpos..@source.length-1]}"
        end
      end
    end

    if !@token[1].nil?
      @curpos = @curpos + @token[1].length
    end
    @last_token = @token
    return @token
  end
...end xsm_expression_parser.racc/module_eval...
##### State transition tables begin ###

racc_action_table = [
    -3,   149,    -3,   102,    21,    22,    89,    33,    35,    24,
    63,   102,     8,   102,    49,    20,   113,    30,   100,    18,
    23,    28,    24,   101,   106,    60,    61,    24,   -70,   -70,
    36,   119,    18,    23,    28,    11,    15,    18,    23,    28,
   150,   -11,   147,    40,     1,     5,    -3,    75,    -3,    76,
    21,    22,    78,    33,    35,   136,   116,   117,     8,    50,
    51,    20,   119,    30,    55,    69,    70,    71,    72,    85,
    86,    22,   107,    24,    35,    55,    36,    53,    54,    52,
   -11,    11,    15,    18,    23,    28,    73,    24,   114,    40,
     1,     5,   122,    24,    85,    86,    36,    18,    23,    28,
   123,    11,    15,    18,    23,    28,    24,    71,    72,    40,
     1,     5,    22,   -12,    33,    35,    18,    23,    28,     8,
    71,    72,    20,    68,    30,    53,    54,    52,    24,    53,
    54,    52,    22,    67,    24,    35,   151,    36,    18,    23,
    28,   152,    11,    15,    18,    23,    28,    55,    24,    65,
    40,     1,     5,    22,    24,    55,    35,    36,    18,    23,
    28,   157,    11,    15,    18,    23,    28,    71,    72,    24,
    40,     1,     5,    22,   124,    24,    35,   nil,    36,    18,
    23,    28,   nil,    11,    15,    18,    23,    28,    24,    71,
    72,    40,     1,     5,   nil,    24,    85,    86,    18,    23,
    28,    85,    86,    11,    15,    18,    23,    28,    83,    84,
   nil,    40,     1,     5,    22,   nil,    33,    35,    88,    87,
   nil,     8,    88,    87,    20,   nil,    30,    44,    45,    46,
    47,    71,    72,   nil,    22,   nil,    24,    35,   nil,    36,
    44,    45,    46,    47,    11,    15,    18,    23,    28,    83,
    84,   nil,    40,     1,     5,   nil,    24,    85,    86,    36,
    44,    45,    46,    47,    11,    15,    18,    23,    28,    85,
    86,   nil,    40,     1,     5,    22,   nil,    33,    35,    71,
    72,   nil,     8,    71,    72,    20,   nil,    30,    69,    70,
    71,    72,    88,    87,   nil,    22,   nil,    24,    35,   nil,
    36,    69,    70,    71,    72,    11,    15,    18,    23,    28,
    85,    86,   nil,    40,     1,     5,   nil,    24,   nil,   nil,
    36,   nil,   nil,   nil,   nil,    11,    15,    18,    23,    28,
   nil,   nil,   nil,    40,     1,     5,    22,   nil,    33,    35,
   nil,   nil,   nil,     8,   nil,   nil,    20,   nil,    30,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,
   nil,    36,   nil,   nil,   nil,   nil,    11,    15,    18,    23,
    28,   nil,   nil,   nil,    40,     1,     5,    22,   nil,    33,
    35,   nil,   nil,   nil,     8,   nil,   nil,    20,   nil,    30,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,   nil,    24,
    35,   nil,    36,   nil,   nil,   nil,   nil,    11,    15,    18,
    23,    28,   nil,   nil,   nil,    40,     1,     5,    22,    24,
   nil,    35,    36,   nil,   nil,   nil,   nil,    11,    15,    18,
    23,    28,   nil,   nil,   nil,    40,     1,     5,   nil,   nil,
    24,   nil,   nil,    36,   nil,   nil,   nil,   nil,    11,    15,
    18,    23,    28,   nil,   nil,   nil,    40,     1,     5,    22,
   nil,    33,    35,   nil,   nil,   nil,     8,   nil,   nil,    20,
   nil,    30,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    24,   nil,   nil,    36,   nil,   nil,   nil,   nil,    11,
    15,    18,    23,    28,   nil,   nil,   nil,    40,     1,     5,
    22,   nil,    33,    35,   nil,   nil,   nil,     8,   nil,   nil,
    20,   nil,    30,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,    36,   nil,   nil,   nil,   nil,
    11,    15,    18,    23,    28,   nil,   nil,   nil,    40,     1,
     5,    22,   nil,    33,    35,   nil,   nil,   nil,     8,   nil,
   nil,    20,   nil,    30,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,    24,   nil,   nil,    36,   nil,   nil,   nil,
   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,    40,
     1,     5,    22,   nil,    33,    35,   -85,   nil,   nil,     8,
   nil,   nil,    20,   nil,    30,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    22,   nil,    24,    35,   nil,    36,   nil,   nil,
   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,
    40,     1,     5,   nil,    24,   nil,   nil,    36,   nil,   nil,
   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,
    40,     1,     5,    22,   nil,    33,    35,   nil,   nil,   nil,
     8,   nil,   nil,    20,   nil,    30,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,    36,   nil,
   nil,   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,
   nil,    40,     1,     5,    22,   nil,    33,    35,   nil,   nil,
   nil,     8,   nil,   nil,    20,   nil,    30,    22,   nil,   nil,
    35,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,    36,
   nil,   nil,   nil,   nil,    11,    15,    18,    23,    28,    24,
   nil,   nil,    40,     1,     5,   nil,   nil,    11,    15,    18,
    23,    28,   nil,   nil,   nil,    40,     1,     5,    22,   nil,
    33,    35,   nil,   nil,   nil,     8,   nil,   nil,    20,   nil,
    30,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    22,   nil,
    24,    35,   nil,    36,   nil,   nil,   nil,   nil,    11,    15,
    18,    23,    28,   nil,   nil,   nil,    40,     1,     5,    22,
    24,   nil,    35,    36,   nil,   nil,   nil,   nil,    11,    15,
    18,    23,    28,   nil,   nil,   nil,    40,     1,     5,    22,
   nil,    24,    35,   nil,    36,   nil,   nil,   nil,   nil,    11,
    15,    18,    23,    28,   nil,   nil,   nil,    40,     1,     5,
    22,    24,   nil,    35,    36,   nil,   nil,   nil,   nil,    11,
    15,    18,    23,    28,   nil,   nil,   nil,    40,     1,     5,
   nil,   nil,    24,   nil,   nil,    36,   nil,   nil,   nil,   nil,
    11,    15,    18,    23,    28,   nil,   nil,   nil,    40,     1,
     5,    22,   nil,    33,    35,   -85,   nil,   nil,     8,   nil,
   nil,    20,   nil,    30,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    22,   nil,    24,    35,   nil,    36,   nil,   nil,   nil,
   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,    40,
     1,     5,    22,    24,   nil,    35,    36,   nil,   nil,   nil,
   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,    40,
     1,     5,    22,   nil,    24,    35,   nil,    36,   nil,   nil,
   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,
    40,     1,     5,    22,    24,   nil,    35,    36,   nil,   nil,
   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,   nil,
    40,     1,     5,    22,   nil,    24,    35,   nil,    36,   nil,
   nil,   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,
   nil,    40,     1,     5,    22,    24,   nil,    35,    36,   nil,
   nil,   nil,   nil,    11,    15,    18,    23,    28,   nil,   nil,
   nil,    40,     1,     5,   nil,   nil,    24,   nil,   nil,    36,
   nil,   nil,   nil,   nil,    11,    15,    18,    23,    28,   nil,
   nil,   nil,    40,     1,     5 ]

racc_action_check = [
     0,   145,     0,    74,     0,     0,    43,     0,     0,    11,
    14,    66,     0,    56,     5,     0,    74,     0,    55,    11,
    11,    11,    51,    56,    66,    14,    14,     0,    11,    11,
     0,   104,    51,    51,    51,     0,     0,     0,     0,     0,
   145,   144,   121,     0,     0,     0,    76,    31,    76,    31,
    76,    76,    33,    76,    76,   103,    77,    77,    76,     6,
     6,    76,    77,    76,   102,   144,   144,   144,   144,   141,
   141,    45,    67,    76,    45,    30,    76,     7,     7,     7,
   144,    76,    76,    76,    76,    76,    28,    85,    75,    76,
    76,    76,    79,    45,   140,   140,    45,    85,    85,    85,
    80,    45,    45,    45,    45,    45,    15,    90,    90,    45,
    45,    45,   157,   142,   157,   157,    15,    15,    15,   157,
    91,    91,   157,    25,   157,   111,   111,   111,    50,   112,
   112,   112,    84,    21,   157,    84,   146,   157,    50,    50,
    50,   147,   157,   157,   157,   157,   157,    20,   117,    19,
   157,   157,   157,    83,    84,     8,    83,    84,   117,   117,
   117,   156,    84,    84,    84,    84,    84,    92,    92,   116,
    84,    84,    84,    65,    81,    83,    65,   nil,    83,   116,
   116,   116,   nil,    83,    83,    83,    83,    83,    86,    93,
    93,    83,    83,    83,   nil,    65,    95,    95,    86,    86,
    86,    96,    96,    65,    65,    65,    65,    65,   132,   132,
   nil,    65,    65,    65,   106,   nil,   106,   106,   127,   127,
   nil,   106,   126,   126,   106,   nil,   106,     3,     3,     3,
     3,   125,   125,   nil,    87,   nil,   106,    87,   nil,   106,
   130,   130,   130,   130,   106,   106,   106,   106,   106,    38,
    38,   nil,   106,   106,   106,   nil,    87,    64,    64,    87,
   131,   131,   131,   131,    87,    87,    87,    87,    87,    59,
    59,   nil,    87,    87,    87,   152,   nil,   152,   152,   109,
   109,   nil,   152,   110,   110,   152,   nil,   152,    26,    26,
    26,    26,    42,    42,   nil,   149,   nil,   152,   149,   nil,
   152,   155,   155,   155,   155,   152,   152,   152,   152,   152,
    41,    41,   nil,   152,   152,   152,   nil,   149,   nil,   nil,
   149,   nil,   nil,   nil,   nil,   149,   149,   149,   149,   149,
   nil,   nil,   nil,   149,   149,   149,    61,   nil,    61,    61,
   nil,   nil,   nil,    61,   nil,   nil,    61,   nil,    61,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    61,   nil,
   nil,    61,   nil,   nil,   nil,   nil,    61,    61,    61,    61,
    61,   nil,   nil,   nil,    61,    61,    61,   107,   nil,   107,
   107,   nil,   nil,   nil,   107,   nil,   nil,   107,   nil,   107,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    88,   nil,   107,
    88,   nil,   107,   nil,   nil,   nil,   nil,   107,   107,   107,
   107,   107,   nil,   nil,   nil,   107,   107,   107,    89,    88,
   nil,    89,    88,   nil,   nil,   nil,   nil,    88,    88,    88,
    88,    88,   nil,   nil,   nil,    88,    88,    88,   nil,   nil,
    89,   nil,   nil,    89,   nil,   nil,   nil,   nil,    89,    89,
    89,    89,    89,   nil,   nil,   nil,    89,    89,    89,    78,
   nil,    78,    78,   nil,   nil,   nil,    78,   nil,   nil,    78,
   nil,    78,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    78,   nil,   nil,    78,   nil,   nil,   nil,   nil,    78,
    78,    78,    78,    78,   nil,   nil,   nil,    78,    78,    78,
   100,   nil,   100,   100,   nil,   nil,   nil,   100,   nil,   nil,
   100,   nil,   100,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   100,   nil,   nil,   100,   nil,   nil,   nil,   nil,
   100,   100,   100,   100,   100,   nil,   nil,   nil,   100,   100,
   100,   123,   nil,   123,   123,   nil,   nil,   nil,   123,   nil,
   nil,   123,   nil,   123,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   123,   nil,   nil,   123,   nil,   nil,   nil,
   nil,   123,   123,   123,   123,   123,   nil,   nil,   nil,   123,
   123,   123,    35,   nil,    35,    35,    35,   nil,   nil,    35,
   nil,   nil,    35,   nil,    35,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    36,   nil,    35,    36,   nil,    35,   nil,   nil,
   nil,   nil,    35,    35,    35,    35,    35,   nil,   nil,   nil,
    35,    35,    35,   nil,    36,   nil,   nil,    36,   nil,   nil,
   nil,   nil,    36,    36,    36,    36,    36,   nil,   nil,   nil,
    36,    36,    36,   119,   nil,   119,   119,   nil,   nil,   nil,
   119,   nil,   nil,   119,   nil,   119,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   119,   nil,   nil,   119,   nil,
   nil,   nil,   nil,   119,   119,   119,   119,   119,   nil,   nil,
   nil,   119,   119,   119,   101,   nil,   101,   101,   nil,   nil,
   nil,   101,   nil,   nil,   101,   nil,   101,    68,   nil,   nil,
    68,   nil,   nil,   nil,   nil,   nil,   101,   nil,   nil,   101,
   nil,   nil,   nil,   nil,   101,   101,   101,   101,   101,    68,
   nil,   nil,   101,   101,   101,   nil,   nil,    68,    68,    68,
    68,    68,   nil,   nil,   nil,    68,    68,    68,   113,   nil,
   113,   113,   nil,   nil,   nil,   113,   nil,   nil,   113,   nil,
   113,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    44,   nil,
   113,    44,   nil,   113,   nil,   nil,   nil,   nil,   113,   113,
   113,   113,   113,   nil,   nil,   nil,   113,   113,   113,    71,
    44,   nil,    71,    44,   nil,   nil,   nil,   nil,    44,    44,
    44,    44,    44,   nil,   nil,   nil,    44,    44,    44,    46,
   nil,    71,    46,   nil,    71,   nil,   nil,   nil,   nil,    71,
    71,    71,    71,    71,   nil,   nil,   nil,    71,    71,    71,
    47,    46,   nil,    47,    46,   nil,   nil,   nil,   nil,    46,
    46,    46,    46,    46,   nil,   nil,   nil,    46,    46,    46,
   nil,   nil,    47,   nil,   nil,    47,   nil,   nil,   nil,   nil,
    47,    47,    47,    47,    47,   nil,   nil,   nil,    47,    47,
    47,    49,   nil,    49,    49,    49,   nil,   nil,    49,   nil,
   nil,    49,   nil,    49,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,    70,   nil,    49,    70,   nil,    49,   nil,   nil,   nil,
   nil,    49,    49,    49,    49,    49,   nil,   nil,   nil,    49,
    49,    49,    69,    70,   nil,    69,    70,   nil,   nil,   nil,
   nil,    70,    70,    70,    70,    70,   nil,   nil,   nil,    70,
    70,    70,    52,   nil,    69,    52,   nil,    69,   nil,   nil,
   nil,   nil,    69,    69,    69,    69,    69,   nil,   nil,   nil,
    69,    69,    69,    53,    52,   nil,    53,    52,   nil,   nil,
   nil,   nil,    52,    52,    52,    52,    52,   nil,   nil,   nil,
    52,    52,    52,    54,   nil,    53,    54,   nil,    53,   nil,
   nil,   nil,   nil,    53,    53,    53,    53,    53,   nil,   nil,
   nil,    53,    53,    53,    72,    54,   nil,    72,    54,   nil,
   nil,   nil,   nil,    54,    54,    54,    54,    54,   nil,   nil,
   nil,    54,    54,    54,   nil,   nil,    72,   nil,   nil,    72,
   nil,   nil,   nil,   nil,    72,    72,    72,    72,    72,   nil,
   nil,   nil,    72,    72,    72 ]

racc_action_pointer = [
     0,   nil,   nil,   204,   nil,     6,    24,    46,   150,   nil,
   nil,   -18,   nil,   nil,   -21,    79,   nil,   nil,   nil,   115,
   142,   128,   nil,   nil,   nil,    89,   261,   nil,    46,   nil,
    70,    47,   nil,    44,   nil,   577,   597,   nil,   230,   nil,
   nil,   275,   271,   -12,   753,    66,   794,   815,   nil,   856,
   101,    -5,   917,   938,   958,     4,    10,   nil,   nil,   234,
   nil,   331,   nil,   nil,   222,   168,     8,    66,   692,   897,
   876,   774,   979,   nil,     0,    88,    46,    21,   454,    83,
    97,   165,   nil,   148,   127,    60,   161,   229,   392,   413,
    78,    91,   138,   160,   nil,   161,   166,   nil,   nil,   nil,
   495,   679,    59,     7,   -10,   nil,   209,   372,   nil,   250,
   254,    94,    98,   733,   nil,   nil,   142,   121,   nil,   638,
   nil,    33,   nil,   536,   nil,   202,   201,   197,   nil,   nil,
   217,   237,   189,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    59,    34,   110,   nil,    38,    -2,    94,   131,   nil,   290,
   nil,   nil,   270,   nil,   nil,   274,   150,   107,   nil ]

racc_action_default = [
   -70,   -82,   -58,   -29,    -7,   -92,   -71,   -39,   -92,    -8,
   -64,   -59,   -42,    -9,   -92,   -70,   -46,   -10,   -68,   -48,
   -92,   -92,   -78,   -72,   -69,   -49,   -32,   -80,   -92,   -52,
   -92,   -92,   -74,   -92,    -1,   -70,   -70,    -4,   -24,    -5,
   -81,   -57,   -26,    -6,   -70,   -70,   -70,   -70,   -83,   -70,
   -70,   -70,   -70,   -70,   -70,   -92,   -92,   -19,   -71,   -60,
   -89,   -70,   -74,   -91,   -61,   -70,   -92,   -92,   -70,   -70,
   -70,   -70,   -70,   -73,   -92,   -92,   -70,   -54,   -70,   -92,
   -86,   -87,   -47,   -70,   -70,   -70,   -70,   -70,   -70,   -70,
   -33,   -34,   -35,   -36,   -87,   -62,   -63,   -45,   -43,   -44,
   -70,   -70,   -92,   -92,   -67,   -50,   -70,   -70,   -51,   -37,
   -38,   -40,   -41,   -70,   159,    -2,   -70,   -70,   -75,   -70,
   -53,   -92,   -84,   -70,   -79,   -32,   -27,   -28,   -65,   -66,
   -31,   -30,   -25,   -21,   -18,   -20,   -90,   -22,   -15,   -23,
   -55,   -56,    -7,   -13,   -32,   -92,   -92,   -92,   -88,   -70,
   -77,   -76,   -70,   -12,   -14,   -11,   -17,   -70,   -16 ]

racc_goto_table = [
    81,    58,   142,   143,    77,    58,    59,    34,    56,   105,
    64,    82,   108,    31,    94,   126,   127,   111,   112,   120,
    66,   128,   129,   130,   131,   132,   103,    97,    98,    99,
    74,   135,   153,   154,   104,   145,    62,    48,   nil,   nil,
    58,    58,   nil,   121,   nil,    95,    96,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    90,    91,    92,    93,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   133,   134,   nil,   nil,   nil,
   nil,   137,   138,   nil,   nil,    58,    58,   nil,   139,   109,
   110,   nil,   nil,   115,   146,   nil,   nil,   nil,   148,   nil,
   nil,   nil,   nil,   125,   125,   nil,   nil,   125,   125,   125,
   nil,   nil,   nil,   nil,   nil,   nil,    58,    58,   nil,   nil,
   nil,   140,   141,   nil,   nil,   nil,   nil,   156,   nil,   nil,
   nil,   nil,   158,   nil,   nil,   nil,   nil,   nil,   nil,   144,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   155 ]

racc_goto_check = [
     3,    29,     6,    10,    25,    29,    27,     2,    13,    21,
    27,    19,    21,     1,     3,    16,    16,    18,    18,    26,
    13,    30,    30,    17,    17,    15,     3,    19,    19,    19,
    13,    14,     6,    10,    25,    12,    32,    34,   nil,   nil,
    29,    29,   nil,     3,   nil,    27,    27,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    11,    11,    11,    11,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,     3,     3,   nil,   nil,   nil,
   nil,     3,     3,   nil,   nil,    29,    29,   nil,     3,    11,
    11,   nil,   nil,     2,     3,   nil,   nil,   nil,     3,   nil,
   nil,   nil,   nil,    11,    11,   nil,   nil,    11,    11,    11,
   nil,   nil,   nil,   nil,   nil,   nil,    29,    29,   nil,   nil,
   nil,    27,    27,   nil,   nil,   nil,   nil,     3,   nil,   nil,
   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,    11,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    11 ]

racc_goto_pointer = [
   nil,    13,     7,   -35,   nil,   nil,  -117,   nil,   nil,   nil,
  -116,    10,   -84,     0,   -71,   -64,   -68,   -64,   -54,   -25,
   nil,   -56,   nil,   nil,   nil,   -28,   -58,    -5,   nil,   -10,
   -64,   nil,    22,   nil,    32,   nil,   nil ]

racc_goto_default = [
   nil,   nil,   nil,    37,    39,    43,     4,     9,    13,    17,
   nil,    26,   nil,   nil,    57,    38,    42,     3,     7,    12,
    16,    19,    25,    29,    32,   nil,   nil,    41,     2,     6,
    10,    14,   nil,   118,    27,    79,    80 ]

racc_reduce_table = [
  0, 0, :racc_error,
  1, 50, :_reduce_1,
  3, 50, :_reduce_2,
  0, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 51, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 52, :_reduce_none,
  1, 59, :_reduce_none,
  1, 59, :_reduce_none,
  1, 61, :_reduce_13,
  3, 61, :_reduce_14,
  4, 53, :_reduce_15,
  8, 56, :_reduce_16,
  6, 56, :_reduce_17,
  4, 57, :_reduce_18,
  1, 62, :_reduce_19,
  3, 62, :_reduce_20,
  3, 63, :_reduce_21,
  4, 58, :_reduce_22,
  4, 58, :_reduce_23,
  1, 54, :_reduce_none,
  3, 54, :_reduce_25,
  1, 64, :_reduce_none,
  3, 64, :_reduce_27,
  3, 64, :_reduce_28,
  1, 65, :_reduce_none,
  3, 65, :_reduce_30,
  3, 65, :_reduce_31,
  1, 66, :_reduce_none,
  3, 66, :_reduce_33,
  3, 66, :_reduce_34,
  3, 66, :_reduce_35,
  3, 66, :_reduce_36,
  3, 55, :_reduce_37,
  3, 55, :_reduce_38,
  1, 60, :_reduce_none,
  3, 60, :_reduce_40,
  3, 60, :_reduce_41,
  1, 67, :_reduce_none,
  3, 67, :_reduce_43,
  3, 67, :_reduce_44,
  3, 67, :_reduce_45,
  1, 68, :_reduce_none,
  2, 68, :_reduce_47,
  1, 69, :_reduce_none,
  1, 69, :_reduce_49,
  3, 71, :_reduce_50,
  3, 71, :_reduce_51,
  1, 70, :_reduce_52,
  3, 70, :_reduce_53,
  0, 75, :_reduce_none,
  2, 75, :_reduce_55,
  2, 75, :_reduce_56,
  1, 72, :_reduce_none,
  1, 72, :_reduce_none,
  1, 77, :_reduce_59,
  2, 77, :_reduce_60,
  2, 77, :_reduce_61,
  3, 77, :_reduce_62,
  3, 77, :_reduce_63,
  1, 76, :_reduce_64,
  3, 76, :_reduce_65,
  3, 76, :_reduce_66,
  3, 79, :_reduce_67,
  1, 79, :_reduce_68,
  1, 79, :_reduce_69,
  0, 80, :_reduce_none,
  1, 80, :_reduce_none,
  1, 80, :_reduce_72,
  2, 78, :_reduce_73,
  0, 74, :_reduce_74,
  2, 74, :_reduce_75,
  3, 82, :_reduce_76,
  3, 82, :_reduce_77,
  1, 73, :_reduce_78,
  3, 73, :_reduce_79,
  1, 73, :_reduce_none,
  1, 73, :_reduce_81,
  1, 73, :_reduce_82,
  2, 73, :_reduce_83,
  3, 83, :_reduce_84,
  0, 84, :_reduce_85,
  1, 84, :_reduce_none,
  1, 85, :_reduce_87,
  3, 85, :_reduce_88,
  1, 81, :_reduce_none,
  3, 81, :_reduce_90,
  1, 81, :_reduce_none ]

racc_reduce_n = 92

racc_shift_n = 159

racc_token_table = {
  false => 0,
  :error => 1,
  :SEMI => 2,
  :COMMA => 3,
  :LET => 4,
  :DOLLAR_QNAME => 5,
  :COLON_EQUAL => 6,
  :IF => 7,
  :LP => 8,
  :RP => 9,
  :THEN => 10,
  :ELSE => 11,
  :FOR => 12,
  :RETURN => 13,
  :IN => 14,
  :SOME => 15,
  :SATISFIES => 16,
  :EVERY => 17,
  :OR => 18,
  :AND => 19,
  :EXCEPT => 20,
  :EQ => 21,
  :NEQ => 22,
  :LT => 23,
  :GT => 24,
  :LTE => 25,
  :GTE => 26,
  :DOT_DOT => 27,
  :TO => 28,
  :PLUS => 29,
  :MINUS => 30,
  :STAR => 31,
  :DIV => 32,
  :MOD => 33,
  :PIPE => 34,
  :SLASH => 35,
  :SLASH_SLASH => 36,
  :DOT => 37,
  :AT => 38,
  :AXIS_NAME => 39,
  :COLON_COLON => 40,
  :LB => 41,
  :RB => 42,
  :LITERAL => 43,
  :NUMBER => 44,
  :FUNCTION_NAME => 45,
  :QNAME => 46,
  :LC => 47,
  :RC => 48 }

racc_nt_base = 49

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "SEMI",
  "COMMA",
  "LET",
  "DOLLAR_QNAME",
  "COLON_EQUAL",
  "IF",
  "LP",
  "RP",
  "THEN",
  "ELSE",
  "FOR",
  "RETURN",
  "IN",
  "SOME",
  "SATISFIES",
  "EVERY",
  "OR",
  "AND",
  "EXCEPT",
  "EQ",
  "NEQ",
  "LT",
  "GT",
  "LTE",
  "GTE",
  "DOT_DOT",
  "TO",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "MOD",
  "PIPE",
  "SLASH",
  "SLASH_SLASH",
  "DOT",
  "AT",
  "AXIS_NAME",
  "COLON_COLON",
  "LB",
  "RB",
  "LITERAL",
  "NUMBER",
  "FUNCTION_NAME",
  "QNAME",
  "LC",
  "RC",
  "$start",
  "statements",
  "statement",
  "expr",
  "let_expr",
  "or_expr",
  "range_expr",
  "if_expr",
  "for_expr",
  "quant_expr",
  "num_expr",
  "additive_expr",
  "num_list",
  "for_vars",
  "for_var",
  "and_expr",
  "equality_expr",
  "relational_expr",
  "multiplicative_expr",
  "unary_expr",
  "union_expr",
  "path_expr",
  "union_expr_x",
  "location_path",
  "primary_expr",
  "predicates",
  "segment",
  "relative_location_path",
  "absolute_location_path",
  "axis_name",
  "step",
  "axis",
  "node_test",
  "predicate",
  "list",
  "opt_args",
  "args" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 10)
  def _reduce_1(val, _values, result)
     result = Fabulator::Expr::StatementList.new; result.add_statement(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 11)
  def _reduce_2(val, _values, result)
     result = val[0]; result.add_statement(val[2]) 
    result
  end
.,.,

# reduce 3 omitted

# reduce 4 omitted

# reduce 5 omitted

# reduce 6 omitted

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 26)
  def _reduce_13(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 27)
  def _reduce_14(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 29)
  def _reduce_15(val, _values, result)
     result = Fabulator::Expr::LetExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 32)
  def _reduce_16(val, _values, result)
     result = Fabulator::Expr::IfExpr.new(val[2], val[5], val[7]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 33)
  def _reduce_17(val, _values, result)
     result = Fabulator::Expr::IfExpr.new(val[2], val[5], nil) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 35)
  def _reduce_18(val, _values, result)
     result = Fabulator::Expr::ForExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 37)
  def _reduce_19(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 38)
  def _reduce_20(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 40)
  def _reduce_21(val, _values, result)
     result = Fabulator::Expr::ForVar.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 42)
  def _reduce_22(val, _values, result)
     result = Fabulator::Expr::SomeExpr.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 43)
  def _reduce_23(val, _values, result)
     result = Fabulator::Expr::EveryExpr.new(val[1], val[3]) 
    result
  end
.,.,

# reduce 24 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 46)
  def _reduce_25(val, _values, result)
     result = Fabulator::Expr::OrExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 26 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 49)
  def _reduce_27(val, _values, result)
     result = Fabulator::Expr::AndExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 50)
  def _reduce_28(val, _values, result)
     result = Fabulator::Expr::ExceptExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 29 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 53)
  def _reduce_30(val, _values, result)
     result = Fabulator::Expr::EqExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 54)
  def _reduce_31(val, _values, result)
     result = Fabulator::Expr::NeqExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 32 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 57)
  def _reduce_33(val, _values, result)
     result = Fabulator::Expr::LtExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 58)
  def _reduce_34(val, _values, result)
     result = Fabulator::Expr::LtExpr.new(val[2], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 59)
  def _reduce_35(val, _values, result)
     result = Fabulator::Expr::LteExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 60)
  def _reduce_36(val, _values, result)
     result = Fabulator::Expr::LteExpr.new(val[2], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 62)
  def _reduce_37(val, _values, result)
     result = Fabulator::Expr::RangeExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 63)
  def _reduce_38(val, _values, result)
     result = Fabulator::Expr::RangeExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 39 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 66)
  def _reduce_40(val, _values, result)
     result = Fabulator::Expr::AddExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 67)
  def _reduce_41(val, _values, result)
     result = Fabulator::Expr::SubExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 42 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 70)
  def _reduce_43(val, _values, result)
     result = Fabulator::Expr::MpyExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 71)
  def _reduce_44(val, _values, result)
     result = Fabulator::Expr::DivExpr.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 72)
  def _reduce_45(val, _values, result)
     result = Fabulator::Expr::ModExpr.new(val[0], val[2]) 
    result
  end
.,.,

# reduce 46 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 75)
  def _reduce_47(val, _values, result)
     result = Fabulator::Expr::NegExpr.new(val[1]) 
    result
  end
.,.,

# reduce 48 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 78)
  def _reduce_49(val, _values, result)
     result = Fabulator::Expr::UnionExpr.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 80)
  def _reduce_50(val, _values, result)
     result = [ val[0], val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 81)
  def _reduce_51(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 83)
  def _reduce_52(val, _values, result)
     result = Fabulator::Expr::PathExpr.new(nil, [], val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 84)
  def _reduce_53(val, _values, result)
     result = Fabulator::Expr::PathExpr.new(val[0], val[1], val[2]) 
    result
  end
.,.,

# reduce 54 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 87)
  def _reduce_55(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 88)
  def _reduce_56(val, _values, result)
     result = [ Fabulator::Expr::AxisDescendentOrSelf.new ] + val[1] 
    result
  end
.,.,

# reduce 57 omitted

# reduce 58 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 96)
  def _reduce_59(val, _values, result)
     result = Fabulator::Expr::RootContext.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 97)
  def _reduce_60(val, _values, result)
     result = Fabulator::Expr::PathExpr.new(Fabulator::Expr::RootContext.new, [], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 98)
  def _reduce_61(val, _values, result)
     result = [ Fabulator::Expr::RootContext.new, Fabulator::Expr::AxisDescendentOrSelf.new(val[1][0]) ] + val[1][1..val[1].size-1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 99)
  def _reduce_62(val, _values, result)
     result = [ Fabulator::Expr::RootContext.new(val[0]) ] + val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 100)
  def _reduce_63(val, _values, result)
     result = [ Fabulator::Expr::RootContext.new(val[0]), Fabulator::Expr::AxisDescendentOrSelf.new(val[2][0]) ] + val[2][1..val[2].size-1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 102)
  def _reduce_64(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 103)
  def _reduce_65(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 104)
  def _reduce_66(val, _values, result)
     result = val[0] + [ Fabulator::Expr::AxisDescendentOrSelf.new(val[2]) ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 106)
  def _reduce_67(val, _values, result)
     result = val[2].nil? || val[2].empty? ? Fabulator::Expr::Step.new(val[0], val[1]) : Fabulator::Expr::Predicates.new(Fabulator::Expr::Step.new(val[0], val[1]), val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 107)
  def _reduce_68(val, _values, result)
     result = Fabulator::Expr::CurrentContext.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 108)
  def _reduce_69(val, _values, result)
     result = Fabulator::Expr::AncestorContext.new 
    result
  end
.,.,

# reduce 70 omitted

# reduce 71 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 116)
  def _reduce_72(val, _values, result)
     result = Fabulator::Expr::Axis.new('attribute')  
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 118)
  def _reduce_73(val, _values, result)
     result = Fabulator::Expr::Axis.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 120)
  def _reduce_74(val, _values, result)
     result = [ ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 121)
  def _reduce_75(val, _values, result)
     result = val[0] + [ val[1] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 123)
  def _reduce_76(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 124)
  def _reduce_77(val, _values, result)
     result = Fabulator::Expr::IndexPredicate.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 128)
  def _reduce_78(val, _values, result)
     result = Fabulator::Expr::Var.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 129)
  def _reduce_79(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 80 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 131)
  def _reduce_81(val, _values, result)
     result = Fabulator::Expr::Literal.new(val[0], [ Fabulator::FAB_NS, 'string' ]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 132)
  def _reduce_82(val, _values, result)
     result = Fabulator::Expr::Literal.new(val[0] =~ /\./ ? val[0].to_f : val[0].to_i, [ Fabulator::FAB_NS, val[0] =~ /\./ ? 'real' : 'integer' ]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 133)
  def _reduce_83(val, _values, result)
     result = Fabulator::Expr::Function.new(@namespaces, val[0], val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 135)
  def _reduce_84(val, _values, result)
     result = Fabulator::Expr::List.new(val[1]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 137)
  def _reduce_85(val, _values, result)
     result = [ ] 
    result
  end
.,.,

# reduce 86 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 140)
  def _reduce_87(val, _values, result)
     result = [ val[0] ] 
    result
  end
.,.,

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 141)
  def _reduce_88(val, _values, result)
     result = val[0] + [ val[2] ] 
    result
  end
.,.,

# reduce 89 omitted

module_eval(<<'.,.,', 'xsm_expression_parser.racc', 144)
  def _reduce_90(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 91 omitted

def _reduce_none(val, _values, result)
  val[0]
end

    end   # class Parser
    end   # module Expr
  end   # module Fabulator
